-- Rollback manual de 202608270002. Ejecutar sólo después de exportar datos.
drop function if exists public.set_platform_admin(uuid,boolean);
drop function if exists public.platform_update_setting(text,jsonb);
drop function if exists public.platform_update_category(uuid,text,boolean,integer);
drop function if exists public.platform_upsert_faq(uuid,text,text,text,integer);
drop function if exists public.platform_add_ticket_note(uuid,text);
drop function if exists public.platform_update_ticket(uuid,text,text);
drop function if exists public.platform_feature_usage();
drop function if exists public.platform_list_users();
drop function if exists public.platform_summary_metrics();
drop function if exists public.set_marketing_preference(boolean,text);
drop function if exists public.record_user_event(text,text,text,text,jsonb);
drop function if exists public.create_feedback_ticket(text,text,text,text,text,text,jsonb);
drop table if exists public.platform_settings;
drop table if exists public.support_faqs;
drop table if exists public.support_categories;
drop table if exists public.admin_audit_log;
drop table if exists public.marketing_preferences;
drop table if exists public.user_events;
drop table if exists public.feedback_admin_notes;
drop table if exists public.feedback_tickets;
delete from storage.buckets where id='feedback-attachments';
alter table public.profiles drop column if exists locale;
alter table public.profiles drop column if exists timezone;
alter table public.profiles drop column if exists last_active_at;
alter table public.profiles drop column if exists onboarding_completed_at;
alter table public.profiles drop column if exists activated_at;
alter table public.profiles drop column if exists session_count;
alter table public.profiles drop column if exists account_status;
